### ISSUE TITLE
 Unable to prepare route [welcome] for serialization. Uses Closure.

### ISSUE THREAD

**Issue by robsontenorio** [mtolhuys/laravel-schematics#11]
web.php
```
Route::get('/welcome', function () {
    return view('welcome');
});
```

```
 php artisan schematics:install
```

Error:
```
 Unable to prepare route [welcome] for serialization. Uses Closure.

  at /var/www/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php:917
```

**Comment by robsontenorio** [comment]
This is related to Laravel itself

**Comment by ejntaylor** [comment]
Sorry, what is the solution here? Are we waiting for core amends to Laravel to cache routes that container closures?

My steps:

laravel new testsite --auth
cd testsite
composer require mtolhuys/laravel-schematics
php artisan schematics:install

**Comment by SlyDave** [comment]
Just to add: You can't use route caching if you use Closures for your routes. (as noted above, this is a Laravel limitation) 

So if this package _requires_ cached routes to work, you can't use this package with Closures.

**Comment by mtolhuys** [comment]
Hi guys! 

Waiting for the last commit to pass the pipeline which includes this commit: https://github.com/mtolhuys/laravel-schematics/pull/24/commits/f7c43bd47e2da8b4f691ae8cdd8d489fbbf22b5f

Will give this output on these cases:

![Screenshot from 2020-03-09 18-28-51](https://user-images.githubusercontent.com/10849136/76241668-9f158d80-6235-11ea-8b01-9b7d6a215781.png)

**Comment by mtolhuys** [comment]
Done! 0.9.11 contains this.
