### ISSUE TITLE
error on schematics:install

### ISSUE THREAD

**Issue by innoflash** [mtolhuys/laravel-schematics#17]
When i run `php artisan schematics:install` I get this error

![Screenshot from 2020-03-07 20-03-35](https://user-images.githubusercontent.com/12772919/76150077-09e88c80-60af-11ea-9c66-8d4ecd2f5855.png)

Let alone the `localhost:8000/schematics` is blank

**Comment by morawcik** [comment]
Fast "fix" - comment out (or delete) default closure routes from api, console and channels file.

**Comment by mtolhuys** [comment]
@innoflash Yeah, what @morawcik says fixes it, relates to https://github.com/mtolhuys/laravel-schematics/issues/11

Laravel doesn't like closures while caching routes. 

In your case its `api/user` where the closure is.
