### ISSUE TITLE
JsonLint Parsing Exception

### ISSUE THREAD

**Issue by nchishti** [mtolhuys/laravel-schematics#27]
When I run: 
`composer  require mtolhuys/laravel-schematics`

I keep getting the following error:

`  [Seld\JsonLint\ParsingException]
  "./composer.lock" does not contain valid JSON
  Parse error on line 742:
            "time": "2020-02-25T
  ---------------------^
  Expected one of: 'EOF', '}', ':', ',', ']'
`

Any ideas why?

**Comment by mtolhuys** [comment]
Hi @nchishti , 

It seems like your `composer.lock` contains some invalid JSON. You could remove it `rm composer.lock` and run `composer install` afterwards.

**Comment by nchishti** [comment]
Yep that fixed it. Thank you.
