### ISSUE TITLE
Support for non-standard model directory path for DDD Laravel Sites

### ISSUE THREAD

**Issue by ejntaylor** [mtolhuys/laravel-schematics#28]
This might be too edge case, but I recently started using a [Laravel boilerplate](https://github.com/hawezo/laravel-boilerplate) which places the Models inside a non-standard location (src/App/) due to using [Domain Driven Design](https://stitcher.io/blog/laravel-beyond-crud-01-domain-oriented-laravel) pattern.. 

Any ideas on supporting a site structure like this? Thanks

**Comment by mtolhuys** [comment]
Hi @raisonon , support for this is coming very soon actually. Top of the list right now.

It will be set through the config where you can point to multiple paths through an array.

**Comment by mtolhuys** [comment]
@raisonon you could try it out with `0.10.0`. 

config now:
```
'model' => [
    'namespace' => 'App\\',
    'paths' => [
        app_path(), \\ Add any path you want the mapper to scan
    ],
],
```

**Comment by cord** [comment]
Reading from a custom path works, however when I try to add a field the POST to `/schematics/models/edit`
fails with Exception
`"message": "Cannot replace non-existing $fillable",`
when hitting the save button.

Drag & drop to sort the new field does not work (can't drop in the list of existing fields)
