### ISSUE TITLE
Stop working after somes tests

### ISSUE THREAD

**Issue by kontas** [mtolhuys/laravel-schematics#41]
Hi, it's an interesting project but it's not working anymore after trying fews things, now i only get this message when i acces to it.

> Symfony\Component\ErrorHandler\Error\FatalError
Cannot declare class App\Policies\User because the name is already in use``

Thanks.

**Comment by mtolhuys** [comment]
Hi @kontas, thanks! 

The problem you're having seems to be related to something else though; did you create `App\Policies\User` with it? There seems to be a duplicate classname in that namespace.

**Comment by kontas** [comment]
Hi @mtolhuys,

I don't remember me creating a policy with or without schematics, but, in did, i have this App\user.php policy : 

`namespace App\Policies;

use App\User;
use Illuminate\Auth\Access\HandlesAuthorization;

class User
{
    use HandlesAuthorization;

    /**
     * Create a new policy instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }
}`

I Juste rename the class, and it's working again.

Did you think i make a mistake with your tools ?

Thanks for your help.

**Comment by mtolhuys** [comment]
No problem @kontas. 

It seems like you created a model or other `User` class under the `App\Policies` namespace. This could've been done through the package if you changed the `config/schematics.php` file to use that namespace. By default it uses the Laravel standard: `namespace App` though. So it won't happen 'out-of-the-box'. It looks like this:

```
    'model' => [
        'namespace' => 'App\\', <---- Namespace for model creation
        'path' => app_path(), <---- Path for model creation
        'paths' => [
            app_path(), <---- Path(s) for model scanning
        ],
    ],
```
