### ISSUE TITLE
Don't run in production env

### ISSUE THREAD

**Issue by mtvbrianking** [mtolhuys/laravel-schematics#42]
Great package 👏👏👏

Is there a way to run schematics on during development, when `config('app.env') != 'production'`?

**Comment by mtolhuys** [comment]
Thanks @mtvbrianking!

I think you could do this in a couple of ways: 

Only require it in development: `composer require mtolhuys/laravel-schematics --dev` 

You could alternatively provide a Middleware to the route through your `config/schematics.php` file.

```
'middleware' => ['dev-env-or-something-similar'],
```

And then handle the check, block and/or redirect through the middleware.

**Comment by mtvbrianking** [comment]
I had required in `--dev` but I could still access the routes in production, I am just worried about users stumbling across the database schematics.

Let me write up a middleware to validate and restrict access based on the app environment.

**Comment by mtvbrianking** [comment]
The middleware option works just fine. I am leaving the steps here it could help someone else.

**Create middleware**

```php
<?php

namespace App\Http\Middleware;

use Closure;

class NotInProduction
{
    public function handle($request, Closure $next)
    {
        if (config('app.env') == 'production') {
            abort(403, "Don't run in production.");
        }

        return $next($request);
    }
}
```

**Register middleware**: `app\Http\Kernel.php`

```php
<?php

namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    // ...

    protected $routeMiddleware = [
        // ...
        
        'dev' => \App\Http\Middleware\NotInProduction::class,
    ];
}
```

**Protect routes**; `config/schematics`

```php
<?php

return [
    // ...
       
    'middleware' => 'dev',
];
```

You may need to clear the cache for the change to be effected.

```bash
php artisan config:clear
```

**Comment by mtolhuys** [comment]
Thanks for sharing @mtvbrianking !
